// Catálogo base de marcas/modelos comunes en yonkes de BC.
// Se fusiona con el catálogo vivo de Firestore (config/catalogoVehiculos).
export const CATALOGO_BASE = {
  'Nissan': ['Sentra', 'Tsuru', 'Versa', 'Altima', 'Maxima', 'March', 'Tiida', 'Pathfinder', 'Xterra', 'Frontier', 'Titan', 'Rogue', 'Murano', 'Juke', 'Kicks', 'NP300', 'Urvan', 'X-Trail', '350Z', 'Quest', 'Armada', 'Aprio', 'Platina'],
  'Toyota': ['Corolla', 'Camry', 'Yaris', 'Avalon', 'Prius', 'RAV4', 'Highlander', '4Runner', 'Sequoia', 'Tacoma', 'Tundra', 'Sienna', 'Matrix', 'Celica', 'Echo', 'Tercel', 'T100', 'Solara', 'Land Cruiser', 'FJ Cruiser'],
  'Chevrolet': ['Aveo', 'Chevy', 'Chevy Pop', 'Spark', 'Sonic', 'Cruze', 'Malibu', 'Impala', 'Cavalier', 'Cobalt', 'Equinox', 'Traverse', 'Trax', 'Tahoe', 'Suburban', 'Silverado', 'Silverado 1500', 'Cheyenne', 'Colorado', 'S10', 'Blazer', 'Trailblazer', 'Astro', 'Express', 'Venture', 'Camaro', 'Monte Carlo', 'HHR', 'Captiva', 'Chevy Van'],
  'Ford': ['Fiesta', 'Focus', 'Fusion', 'Taurus', 'Mustang', 'Escape', 'Edge', 'Explorer', 'Expedition', 'Flex', 'EcoSport', 'Ranger', 'F-150', 'F-250', 'F-350', 'Lobo', 'Transit', 'Econoline', 'Windstar', 'Freestar', 'Escort', 'Contour', 'Courier', 'Bronco', 'Crown Victoria', 'Aerostar'],
  'Honda': ['Civic', 'Accord', 'Fit', 'City', 'CR-V', 'HR-V', 'Pilot', 'Odyssey', 'Element', 'Ridgeline', 'Prelude'],
  'Volkswagen': ['Jetta', 'Golf', 'Beetle', 'Vocho', 'Passat', 'Pointer', 'Lupo', 'Polo', 'Bora', 'Tiguan', 'Touareg', 'Eurovan', 'Combi', 'Derby', 'Caribe', 'Atlantic', 'CrossFox', 'Saveiro', 'Amarok', 'Vento', 'Gol'],
  'Dodge': ['Attitude', 'Neon', 'Stratus', 'Avenger', 'Charger', 'Challenger', 'Dart', 'Journey', 'Durango', 'Caravan', 'Grand Caravan', 'Ram 1500', 'Ram 2500', 'Dakota', 'Nitro', 'Caliber', 'Intrepid', 'Shadow', 'Spirit'],
  'Chrysler': ['300', '300M', 'Cirrus', 'Sebring', 'PT Cruiser', 'Town & Country', 'Voyager', 'Pacifica', 'Concorde', 'LeBaron'],
  'Jeep': ['Wrangler', 'Cherokee', 'Grand Cherokee', 'Liberty', 'Compass', 'Patriot', 'Commander', 'Renegade'],
  'GMC': ['Sierra', 'Yukon', 'Terrain', 'Acadia', 'Envoy', 'Jimmy', 'Savana', 'Sonoma', 'Canyon'],
  'Hyundai': ['Accent', 'Elantra', 'Sonata', 'Tucson', 'Santa Fe', 'Creta', 'Grand i10', 'i10', 'ix35', 'Veloster', 'Tiburon', 'H100'],
  'Kia': ['Rio', 'Forte', 'Optima', 'Soul', 'Sportage', 'Sorento', 'Sedona', 'Spectra'],
  'Mazda': ['2', '3', '5', '6', 'CX-3', 'CX-5', 'CX-7', 'CX-9', 'MX-5', 'B2300', 'B3000', 'Tribute', 'Protege', '626', 'Millenia'],
  'Mitsubishi': ['Lancer', 'Mirage', 'Galant', 'Eclipse', 'Outlander', 'Montero', 'L200', 'Endeavor'],
  'Buick': ['Century', 'LeSabre', 'Regal', 'LaCrosse', 'Enclave', 'Rendezvous', 'Park Avenue', 'Rainier', 'Verano', 'Encore'],
  'Pontiac': ['Grand Am', 'Grand Prix', 'Bonneville', 'Sunfire', 'Aztek', 'Montana', 'G3', 'G5', 'G6', 'Matiz', 'Firebird', 'Vibe', 'Torrent'],
  'Oldsmobile': ['Alero', 'Cutlass', 'Intrigue', 'Aurora', 'Bravada', 'Silhouette'],
  'Saturn': ['Ion', 'Vue', 'Aura', 'Outlook', 'SL', 'SC', 'LS'],
  'Cadillac': ['DeVille', 'Escalade', 'CTS', 'STS', 'SRX', 'Seville', 'Eldorado', 'ATS', 'XTS'],
  'Lincoln': ['Town Car', 'Continental', 'Navigator', 'MKX', 'MKZ', 'MKS', 'MKC', 'Aviator', 'LS', 'Mark LT'],
  'Mercury': ['Grand Marquis', 'Sable', 'Mountaineer', 'Milan', 'Mariner', 'Cougar', 'Villager'],
  'Subaru': ['Impreza', 'Legacy', 'Outback', 'Forester', 'Tribeca', 'XV'],
  'Suzuki': ['Swift', 'Aerio', 'SX4', 'Grand Vitara', 'XL7', 'Forenza', 'Verona', 'Kizashi'],
  'BMW': ['Serie 1', 'Serie 3', 'Serie 5', 'Serie 7', '323i', '325i', '328i', '750i', 'X1', 'X3', 'X5', 'X6', 'Z4'],
  'Mercedes-Benz': ['Clase A', 'Clase B', 'Clase C', 'Clase E', 'C230', 'ML320', 'ML350', 'GLA', 'GLC', 'GLE', 'Sprinter'],
  'Audi': ['A3', 'A4', 'A6', 'Q3', 'Q5', 'Q7', 'TT'],
  'Acura': ['TL', 'TSX', 'RL', 'MDX', 'RDX', 'Integra', 'ILX'],
  'Infiniti': ['G35', 'G37', 'I30', 'I35', 'FX35', 'QX56', 'QX60', 'M35'],
  'Lexus': ['ES300', 'IS300', 'GS300', 'LS', 'RX', 'GX', 'LX', 'CT200h'],
  'Volvo': ['S40', 'S60', 'S80', 'V50', 'V70', 'XC60', 'XC70', 'XC90', 'C30'],
  'Renault': ['Clio', 'Megane', 'Sandero', 'Duster', 'Logan', 'Stepway', 'Koleos', 'Kangoo', 'Platina', 'Scenic'],
  'Peugeot': ['206', '207', '208', '301', '307', '308', '3008', 'Partner', 'Manager'],
  'SEAT': ['Ibiza', 'León', 'Toledo', 'Altea', 'Córdoba', 'Ateca'],
  'Fiat': ['500', 'Palio', 'Uno', 'Mobi', 'Ducato', 'Strada'],
  'RAM': ['700', '1500', '2500', '4000', 'ProMaster'],
  'Isuzu': ['Rodeo', 'Trooper', 'Amigo', 'Ascender', 'ELF', 'NPR'],
  'Hummer': ['H1', 'H2', 'H3'],
  'Scion': ['tC', 'xB', 'xD', 'xA', 'FR-S'],
  'Geo': ['Prizm', 'Metro', 'Tracker'],
  'Land Rover': ['LR3', 'LR4', 'Discovery', 'Range Rover', 'Freelander'],
  'Mini': ['Cooper', 'Countryman', 'Clubman'],
  'Smart': ['Fortwo', 'Forfour'],
};